apiVersion: v1
kind: ConfigMap
metadata:
  name: ingestor-config
data:
  MQTT_HOST: "mosquitto"
  MQTT_PORT: "1883"
  MQTT_TOPICS: "int/+/accel"
  MQTT_CLIENT_ID: "ingestor-$(HOSTNAME)"
  MQTT_KEEPALIVE: "30"
  MQTT_QOS: "1"
  MQTT_CLEAN_SESSION: "false"
  PG_HOST: "postgres"
  PG_PORT: "5432"
  PG_DB: "runsense"
  RAW_TABLE: "raw_windows"
  FEAT_TABLE: "features"
  HTTP_PORT: "8080"
  LOG_LEVEL: "info"
