apiVersion: apps/v1
kind: Deployment
metadata:
  name: ingestor
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ingestor
  template:
    metadata:
      labels:
        app: ingestor
    spec:
      containers:
        - name: ingestor
          image: yourrepo/ingestor:dev
          imagePullPolicy: IfNotPresent
          envFrom:
            - configMapRef:
                name: ingestor-config
            - secretRef:
                name: ingestor-secret
            - secretRef:
                name: pg-secret
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 20
            periodSeconds: 10
